version: '3.8'

services:
  database:
    image: postgres:15
    ports:
      - "5435:5432"
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - back_end/src/main/resources/secrets.properties

volumes:
  database:
