version: '3.8'

services:
  database:
    image: postgres:15
    ports:
      - "5435:5432"
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - back_end/src/main/resources/secrets.properties
    restart: unless-stopped

  backend:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/zaiets_website
    restart: unless-stopped

  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  database:
